<?php

namespace Tests\Unit;

use App\Models\Order;
use App\Models\UserHasCoupon;
use App\Models\Users;
use App\Services\CouponService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\RefreshDatabaseState;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class CouponTest extends TestCase
{
//    use RefreshDatabase;
    /**
     * @var CouponService
     */
    protected $couponService;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
//        RefreshDatabaseState::$migrated = true;
//        $this->refreshDatabase();
        $this->couponService = new CouponService();
        $this->app['auth']->loginUsingId(15);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testDistribute()
    {
        $result = $this->couponService->distributeCoupon(15, 10, 0.02, CouponService::TRIGGER_AFTER_PAID,
            UserHasCoupon::SOURCE_TYPE_TEST, 0);
        $this->assertEquals(1, $result);
    }

    public function testChooseCoupon()
    {
        $result = $this->couponService->chooseCoupon(30, 0, 0.02);
        var_dump($result);
    }
}
